# .readthedocs.yml

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Non-HTML is useless until the docs are much longer
formats: []

python:
  version: 3.6
  install:
       path: .
  system_packages: true